lexik_jwt_authentication:
  private_key_path: "%env(jwt_private_key_path)%"
  public_key_path: "%%env(jwt_public_key_path)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: "%env(jwt_token_ttl)%"
