#index:
#    path: /
#    controller: App\Controller\DefaultController::index
movies:
  type: rest
  resource: App\Controller\MoviesController
movies_post:
  path: /movies
  methods: [POST]
  defaults:
    _controller: App\Controller\MoviesController:postMoviesAction
    _format: json
movies_patch:
  path: /movies/{movie}
  methods: [PATCH]
  defaults:
    _controller: App\Controller\MoviesController:patchMovieAction
    _format: json

humans:
  type: rest
  resource: App\Controller\HumansController
humans_post:
  path: /humans
  methods: [POST]
  defaults:
    _controller: App\Controller\HumansController:postHumansAction
    _format: json

movies_roles_post:
  path: /movies/{movie}/roles
  methods: [POST]
  defaults:
    _controller: App\Controller\MoviesController:postMovieRolesAction
    _format: json

user:
  resource: App\Controller\UsersController
  type: rest

users_post:
  path: /users
  methods: [POST]
  defaults:
    _controller: App\Controller\UsersController:postUserAction
    _format: json
users_patch:
  path: /users/{theUser}
  methods: [PATCH]
  defaults:
    _controller: App\Controller\UsersController:patchUserAction
    _format: json

tokens:
  resource: App\Controller\TokensController
  type: rest
tokens_post:
  path: /tokens
  methods: [POST]
  defaults:
    _controller: App\Controller\TokensController:postTokenAction
    _format: json

images:
  resource: App\Controller\ImagesController
  type: rest

images_post:
  path: /images
  methods: [POST]
  defaults:
    _controller: App\Controller\ImagesController:postImagesAction
    _format: json

images_upload_put:
  path: /images/{image}/upload
  methods: [PUT]
  defaults:
    _controller: App\Controller\ImagesController:putImageUploadAction
