#index:
#    path: /
#    controller: App\Controller\DefaultController::index
movies:
  type: rest
  resource: App\Controller\MoviesController
movies_post:
  path: /movies
  methods: [POST]
  defaults:
    _controller: App\Controller\MoviesController:postMoviesAction
    _format: json

humans:
  type: rest
  resource: App\Controller\HumansController
humans_post:
  path: /humans
  methods: [POST]
  defaults:
    _controller: App\Controller\HumansController:postHumansAction
    _format: json
