#index:
#    path: /
#    controller: App\Controller\DefaultController::index
movies:
  type: rest
  resource: App\Controller\MoviesController
movies_post:
  path: /movies
  methods: [POST]
  defaults:
    _controller: App\Controller\MoviesController:postMoviesAction
    _format: json
movies_patch:
  path: /movies/{movie}
  methods: [PATCH]
  defaults:
    _controller: App\Controller\MoviesController:patchMovieAction
    _format: json

humans:
  type: rest
  resource: App\Controller\HumansController
humans_post:
  path: /humans
  methods: [POST]
  defaults:
    _controller: App\Controller\HumansController:postHumansAction
    _format: json

movies_roles_post:
  path: /movies/{movie}/roles
  methods: [POST]
  defaults:
    _controller: App\Controller\MoviesController:postMovieRolesAction
    _format: json

user:
  resource: App\Controller\UserController
  type: annotation
